#!/bin/bash
export NVOC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${NVOC}/1bash"

ALGOS="ETHASH EQUIHASH"

for ALGO in $ALGOS
do
  eval 'ALGO_COINS=${ALGO}_COINS'
  if [[ "${!ALGO_COINS}"  =~ "$COIN" ]]
  then
    ALGO="$ALGO" 
    #echo "$ALGO"
  fi
done
