#!/bin/bash
export NVOC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${NVOC}/1bash"
ALGO="UNDEFINED"

ALGOS="NEOSCRYPT ETHASH EQUIHASH SKUNK LYRA2V2 CRYPTONIGHT LYRA2Z XEVAN X16R BITCORE SIB CRYPTONIGHTV7 PHI PASCAL LBRY GRS MYR_GR DECRED SIA X13 SKEIN CRYPTONIGHTHEAVY ZHASH "

if [[ $COIN == "" ]]
then
  COIN="none"
fi

for a in $ALGOS
do
  ALGO_COINS=${a}_COINS
  if [[ ${!ALGO_COINS} =~ $COIN ]]
  then
    ALGO=$a
    break
  fi
done
