#!/bin/bash

##########################################################################
##########################################################################
####################   nvOC 3.1 - Community Release   ####################
##########   Based on the original nvOC v0019-1.4 by fullzero   ############
##########################################################################
##########################################################################

# 0miner for nvOC v0019-3.1

# DEV Mod Log:
# v=0001 : papampi: Initial Release
#
# v=0002 : papampi:
#          fix lbc
# v=0003 : papampi:
#          More NiceHash, MINER_PWD failsafe,
#          COIN_EXTENSION_ARGUMENTS for ethminer and genoil
# v=0004 : damNmad:
#          New Coins LUX, SUMO, DSR
# v=0005 : papampi:
#          New Coin ELLA, XVG, GBX, CRC
# v=0006 : papampi:
#          EQUIHASH_MINER, bminer, ETHASH_MINER
# v=0007 : papampi:
#          Nicehash bug fixes
# v=0008 : papampi:
#          Move all miners to "${NVOC}"/miners/
# v=0009 : papampi
#          Pool Wallet Address Format
# v=0010 : papampi
#          New Claymore Dual Mining
# v=0011 : damNmad
#          Added BTCP
# v=0012 : Falcon
#          Added CCMINER_OPTS, added RavenCoin (RVN)
# v=0013 : papampi
#          Changed EWBF HCD
# v=0014 : papampi
#          Code cleanup, NEOSCRYPT_MINER, LYRA2V2_MINER, SKUNK_MINER, SKEIN_MINER
# v=0015 : LukePicci
#          Relocate nvOC to arbitrary install directory
# v=0016 : papampi
#          Prevent running 2 miners
# v=0017 : sizzlephizzle
#	         Unification of EQUIHASH & ETHASH mining by ALGO.
# v=0018 : papampi, sizzlephizzle
#	         Algo Unification for all algorithms
# v=0019 : papampi
#          Crytponight Heavy
# v=0020 : papampi
#          ZHASH, PHI1612, PHI2 Algos and Z_EWBF
# v=0021 : LuKePicci
#          Support pluggable miners
# v=0022 : papampi
#          Ethminer new arguments, Coin Pool Protocol
# v=0023 : papampi
#          Cuda switch in screenrc for new and old miners
# v=0024 : papampi
#          New miners directory and miner version
# v=0025 : papampi
#          BMINER Dual Mining
# v=0026 : papampi
#          lolMiner
# v=0027 : papampi
#          PhoenixMiner
# v=0028 : brightskye
#          disabled_gpu helper
# v=0029 : papampi
#          echo miner command
# v=0030 : LuKePicci
#          remove first batch of legacy miners

nvOC_0miner_dev="0030"
source "${NVOC}/1bash"
source "${NVOC}/helpers/coin_algo_mapping"
source "${NVOC}/helpers/disabled_gpu.sh"

nvOC_0miner_ver="$nvOC_Ver.$nvOC_0miner_dev" # Do not edit this

# Prevent running 2 miners
if ps ax | grep SCREEN | grep -v cpuminer | grep -q miner ; then
  ps ax | grep SCREEN | grep -v cpuminer | grep miner | awk '"miner" {print $1}' | xargs kill -9
fi

# Set MINER_PWD if unset
if [ -z "${MINER_PWD+x}" ]
then
  MINER_PWD="x"
fi

## Unify COIN Start
UPOOL="_POOL"
UPORT="_PORT"
UPROTO="_POOL_PROTOCOL"
UADDR="_ADDRESS"
UWORK="_WORKER"
UCOINOPTS="_OPTS"
UINTENSITY="_INTENSITY"
UWALLET="_WALLET_FORMAT"
UMINER="_MINER"
UFEE="_FEE"
UVERSION="_VERSION"
UCUDA="_CUDA"

xpool=$COIN$UPOOL
xport=$COIN$UPORT
xproto=$COIN$UPROTO
xaddr=$COIN$UADDR
xwork=$COIN$UWORK
xcoinopts=$COIN$UCOINOPTS
xintensity=$ALGO$UINTENSITY
xwallet=$ALGO$UWALLET
xminer=$ALGO$UMINER
xfee=${!xminer}$UFEE
xversion=${!xminer}$UVERSION
xcuda=$ALGO$UCUDA
## Unify COIN End

OPTS="${!xcoinopts} $(dgh_get_miner_opts "${!xminer}" "$COIN" "$ALGO")"

mpath="${NVOC}/miners/${!xminer}"

# List of cuda-8.0 miners
CUDA_8_MINERS="ANXccminer ASccminer KXccminer MSFTccminer NAccminer SILENTminer SPccminer SUPRminer VERTMINER"
LAUNCH="screen -c ${NVOC}/screenrc-miner -dmSL miner"
for miner in $CUDA_8_MINERS
do
  if [[ ${!xminer} =~ $miner ]]; then
    LAUNCH="screen -c ${NVOC}/screenrc-miner-cuda-8 -dmSL miner"
  fi
done

if [[ ${!xaddr} == "" ]]
then
  ## NICEHASH
  if [[ ${COIN:0:4} == NICE ]]
  then
    eval $xaddr="$NICE_ADDRESS"
  ## ZPOOL
  elif [[ ${COIN:0:5} == ZPOOL ]]
  then
    eval $xaddr="$ZPOOL_ADDRESS"
  ## MPH
  elif [[ ${COIN:0:3} == MPH ]]
  then
    eval $xaddr="$MPH_ADDRESS"
  fi
fi

if [[ ${!xaddr} == "" ]]
then
  echo "WARNING: ${xaddr} is empty or not set"
fi

if [[ ${!xproto} == "" ]]
then
  eval $xproto="stratum+tcp"
fi

if [[ ${!xversion} == "" ]]
then
  eval $xversion="recommended"
fi


## CLAYMORE_DUAL
if [[ $COIN == CLAYMORE_DUAL ]]
then
  # add claymore opts?
  # OPTS="$(dgh_enabled_devices '-di ' '' 'A' "$OPTS")"
  HCD=${NVOC}/miners/CLAYMORE/$CLAYMORE_VERSION/ethdcrminer64
  E_ADDR="$DUAL_EWAL""$ETHASH_WALLET_FORMAT""$DUAL_EWORKER"
  D_ADDR="$DUAL_DWAL""$DUAL_WALLET_FORMAT""$DUAL_DWORKER"
  screen -c "${NVOC}"/screenrc-miner -dmSL miner "$HCD" -epool "$DUAL_EPOOL":"$DUAL_EPORT" -ewal "$E_ADDR" -epsw "$DUAL_EPSW" -dpool stratum+tcp://"$DUAL_DPOOL":"$DUAL_DPORT" -dwal "$D_ADDR" -dpsw "$DUAL_DPSW" -dcoin "$DUAL_DCOIN" -allpools "$ALL_POOLS" -dbg -1 -mport "$MPORT" -mpsw "$MPSW" "$DUAL_ADDITIONAL_ARGUMENTS" $OPTS
fi

if [[ $COIN == BMINER_DUAL ]]
then
  HCD=${NVOC}/miners/BMINER/$BMINER_VERSION/bminer
  screen -c "${NVOC}"/screenrc-miner -dmSL miner "$HCD" -uri $MAIN_COIN_POOL_PROTOCOL://$MAIN_COIN_ADDRESS.$MAIN_COIN_WORKER:$MINER_PWD@$MAIN_COIN_POOL:$MAIN_COIN_PORT -uri2 $DUAL_COIN_POOL_PROTOCOL://$DUAL_COIN_ADDRESS.$DUAL_COIN_WORKER:$MINER_PWD@$DUAL_COIN_POOL:$DUAL_COIN_PORT $OPTS
fi


## Pluggable miners
if [[ ${!xversion} != "" && -f ${mpath}/"${!xversion}"/nvoc-miner.json || -f ${mpath}/nvoc-miner.json ]]
then
  pm_manifest=${mpath}/${!xversion}/nvoc-miner.json
  
  # parse device enable params
  dev_enable_arg="$(jq -r .devlist_argument ${pm_manifest})"
  if [[ $dev_enable_arg != "" ]]
  then
    dev_enable_sep="$(jq -r .devlist_separator ${pm_manifest})"
    dev_enable_fmt="$(jq -r .devlist_format ${pm_manifest})"
    $OPTS="$(dgh_enabled_devices '${dev_enable_arg}' '${dev_enable_sep}' '${dev_enable_fmt}' "$OPTS")"
  fi

  if [[ $FOREMAN_MONITOR == YES ]]
  then
    # parse foreman monitor params
    api_ext=$(jq -r .foreman.api_ext ${pm_manifest})
    if [[ $api_ext != "" ]]
    then
      OPTS="$OPTS $api_ext"
    fi
  fi

  HCD="${mpath}/"${!xversion}"/$(jq -r .hcd ${pm_manifest})"
  eval echo $LAUNCH $HCD $OPTS
  eval $LAUNCH $HCD $OPTS


## ETHASH
elif [[ $ALGO == ETHASH ]]
then
  if [[ $ETHASH_MINER == GENOIL ]]
  then
    # skipping GENOIL's setting, since i'm not sure what's it's device options prefix ,etc
    # OPTS="$(dgh_enabled_devices '-di ' '' 'A' "$OPTS")"
    HCD="${NVOC}/miners/Genoil-U/ethminer -S ${!xpool}:${!xport} -O ${!xaddr}${!xwallet}${!xwork}:$MINER_PWD -SP 1 -U $OPTS"
  # Looking for BMINER, CLAYMORE, ETHMINER? They have already been ported to PMs
  elif [[ $ETHASH_MINER == PhoenixMiner ]]
  then
    OPTS="$(dgh_enabled_devices '-gpus ' ',' 'N' "$OPTS")"
    HCD="${NVOC}/miners/PhoenixMiner/"${!xversion}"/PhoenixMiner -pool ${!xproto}://${!xpool}:${!xport} -wal ${!xaddr} -worker ${!xwork} -pass $MINER_PWD $OPTS"
  fi
  eval $LAUNCH $HCD


## EQUIHASH
elif [[ $ALGO == EQUIHASH ]]
then
  if [[ $EQUIHASH_MINER == DSTM ]]
  then
    OPTS="$(dgh_enabled_devices '--dev ' ' ' 'N' "$OPTS")"
    HCD="${NVOC}/miners/DSTM/"${!xversion}"/miner --server ${!xpool} --user ${!xaddr}${!xwallet}${!xwork} --port ${!xport} --pass $MINER_PWD --time $OPTS"
  # Looking for EWBF, BMINER? They have already been ported to PMs
  fi
  eval $LAUNCH $HCD


## ZHASH
elif [[ $ALGO == ZHASH ]]
then
    # Looking for Z_EWBF, BMINER? They have already been ported to PMs
  if [[ $ZHASH_MINER == LOLMINER ]]
  then
    ## Not sure what are the devices options
    OPTS="$(dgh_enabled_devices '--devices ' ',' 'N' "$OPTS")" 
    HCD="${NVOC}/miners/LOLMINER/"${!xversion}"/lolMiner -coin=$COIN -pool=${!xpool} -port=${!xport} -user=${!xaddr}${!xwallet}${!xwork} $OPTS"  
  fi
  eval $LAUNCH $HCD

## Various Algos
elif [[ $ALGO == X22I || $ALGO == X16R || $ALGO == SIB || $ALGO == LYRA2Z || $ALGO == SKUNK || $ALGO == KECCAK || $ALGO == SKEIN || $ALGO == NEOSCRYPT || $ALGO == LYRA2V2 || $ALGO == BITCORE || $ALGO == PHI1612 || $ALGO == PHI2 || $ALGO == LBRY || $ALGO == DMD_GR || $ALGO == GROESTL || $ALGO == MYR_GR || $ALGO == DECRED || $ALGO == SIA || $ALGO == X13 || $ALGO == XEVAN ]]
then
  OPTS="$(dgh_enabled_devices '--devices ' ',' 'N' "$OPTS")"
  UCCALGO="-a ${ALGO,,}"
  HCD="${NVOC}"/miners/"${!xminer}"/"${!xversion}"/ccminer
  eval $LAUNCH $HCD $UCCALGO -o ${!xproto}://"${!xpool}":"${!xport}" -u "${!xaddr}""${!xwallet}""${!xwork}" -p "$MINER_PWD" -i "${!xintensity}" $OPTS


## CRYPTONIGHT
elif [[ $ALGO == CRYPTONIGHT ]]
then
  OPTS="$(dgh_enabled_devices '--devices ' ',' 'N' "$OPTS")"
  # Looking for KTccminer_cryptonight? It has already been ported to PMs
    UCCALGO="-a ${ALGO,,}"
    HCD="${NVOC}"/miners/"${!xminer}"/"${!xversion}"/ccminer
    eval $LAUNCH $HCD $UCCALGO -o ${!xproto}://"${!xpool}":"${!xport}" -u "${!xaddr}""${!xwallet}""${!xwork}" -p "$MINER_PWD" -i "${!xintensity}" $OPTS
  
## CRYPTONIGHTV7
  # Looking for XMR_Stak? It has already been ported to PMs
else
  echo ""
  echo "COIN/ALGO not found, Check your settings"
  echo "Miner not started, Stopping watchdog"
  pkill -f 5watchdog
fi
