#!/bin/bash

firstBOOT="NO"

if grep -q "convert" /home/m1/firstBOOT;
then
  firstBOOT="YES"
fi

if [ $firstBOOT == "YES" ]
then
  echo "First Boot, Copying 1bash and Expanding root partition"
  sleep 5
  rm /home/m1/firstBOOT
  sleep 1
  touch /home/m1/firstBOOT
  if [ -e /media/m1/12D3-A869/1bash ]
  then
    echo "Copying 1bash"
    sudo cp '/media/m1/12D3-A869/1bash' '/home/m1/1bash'
    echo "wait 15 seconds to minimize errors"
    sudo dos2unix /home/m1/1bash
    sleep 15
  else
    echo "Mounting fat partition"
    sudo mkdir -p /media/m1/12D3-A869/
    sudo mount /dev/sda1 /media/m1/12D3-A869
    echo "Copying 1bash from fat partition"
    sudo cp '/media/m1/12D3-A869/1bash' '/home/m1/1bash'
    echo "wait 5 seconds to minimize errors"
    sudo dos2unix /home/m1/1bash
    sleep 5
  fi
  echo "Expanding root partition"
  sleep 1
  sudo bash /home/m1/expand_rootfs.sh
  echo "Root Partition expanded, reboot in 5 seconds"
  sleep 5
  sudo reboot
fi
pkill -f 3main

sleep 3

update="YES"

if grep -q "v0019-2.1" /home/m1/1bash; then
  update="NO"
  echo "nvOC v0019-2.1 - Community Release"
fi

if [ $update == "YES" ] ; then
  echo "Update Available"
fi

bash '/home/m1/3main'
