#!/bin/bash
# 4nvOC_watch to monitor nvOC running scripts

v0001="papampi; Initial release"

source ${NVOC}/1bash
nvOC_4nvOC_watch_Dev="0001"
nvOC_4nvOC_watch_ver="$nvOC_ver.$nvOC_4nvOC_watch_Dev"                

echo "Starting nvOC Watch to monitor nvOC scripts in 60 seconds"
sleep 60

# Infinite Loop
while true
do
  source ${NVOC}/1bash
  echo "$(date) Check nvOC scripts"
  echo "Exit/Close this guake tab if you want to close gnome-terminal and stop mining"
  echo ""
  
  if [[ $AUTO_START_MINER == "YES" ]]
  then
    if ! ps ax | grep -q "[3]main"
    then
      echo "3main is not running, checking 2unix"
      if ! ps ax | grep -q "[2]unix"
      then
        echo "$(date) - 2unix stopped running, restarting it"  | tee -a  ${NVOC}/nvoc_logs/5_watchdoglog
        bash ${NVOC}/nvOC restart
      fi
    else
      echo "3main running"
    fi
  fi
  
  if [[ $MINER_WATCHDOG == "YES" ]]
  then
    if ! ps ax | grep -q "[5]watchdog"
    then
      echo "watchdog stopped running, check again in 30"
      sleep 30
      if ! ps ax | grep -q "[5]watchdog"
      then
        echo "$(date) - watchdog stopped running, restarting it" | tee -a  ${NVOC}/nvoc_logs/5_watchdoglog
        screen -c ${NVOC}/screenrc-watchdog -dmSL wdog bash ${NVOC}/5watchdog
      fi
    else
      echo "WatchDog running"
    fi
  else
    echo "Watchdog disabled"
    if ps ax | grep -q "[5]watchdog"
    then
      pkill -f 5watchdog
    fi
  fi

  if [[ $MINER_TEMP_CONTROL == "YES" ]]
  then
    if ! ps ax | grep -q "[6]tempcontrol"
    then
      echo "tempcontrol stopped running, check again in 30"
      sleep 30
      if ! ps ax | grep -q "[6]tempcontrol"
      then
        echo "$(date) - tempcontrol stopped running, restarting it" | tee -a  ${NVOC}/nvoc_logs/6_autotemplog
        screen -c ${NVOC}/screenrc-tempcontrol -dmSL temp bash ${NVOC}/6tempcontrol
      fi
    else
      echo "Temp Control running"
    fi
  else
    echo "Temp control disabled"
    if ps ax | grep -q "[6]tempcontrol"
    then
      pkill -f 6tempcontrol
    fi
  fi

  if [[ $AUTO_SWITCH == WTM_SWITCHING ]]
  then
    if ! ps ax | grep -q "[8]wtm_auto_switch"
    then
      echo "wtm stopped running, check again in 30"
      sleep 30
      if ! ps ax | grep -q "[8]wtm_auto_switch"
      then
        echo "$(date) - wtm stopped running, restarting it"  | tee -a  ${NVOC}/nvoc_logs/5_watchdoglog
        screen -c ${NVOC}/screenrc-wtm -dmSL wtm bash ${NVOC}/8wtm_auto_switch
      fi
    else
      echo "WTM Auto Switch running"
    fi
  else
    echo "WTM Auto Switch disabled"
    if ps ax | grep -q "[8]wtm_auto_switch"
    then
      pkill -f 8wtm_auto_switch
    fi
  fi
  
  echo "Check again in 5 min"
  echo " "
  sleep 300

done
