#!bin/bash
source ${NVOC}/1bash



while true
do

# If 1, 5 and 15 min load average are more than double cpu core give warning
  HIGH_AVERAGE=$(( $(nproc) * 2 ))
  AVERAGES=$(uptime | sed 's/.*: //g')
  echo "Load Average: $AVERAGES" | tee -a ${NVOC}/5_watchdoglog

# Prevent slow single core cpus gives warning
  if [[ "$HIGH_AVERAGE" < 4 ]]
  then
    HIGH_AVERAGE=4
  fi

  AVERAGE_1=$(echo "$AVERAGES" | cut -d"," -f1)
  if [[ "$AVERAGE_1" > "$HIGH_AVERAGE"  ]]
  then
    AVRG_1="HIGH"
  else
    AVRG_1="OK"
  fi
  AVERAGE_5=$(echo "$AVERAGES" | cut -d"," -f2)
  if [[ "$AVERAGE_5" > "$HIGH_AVERAGE"  ]]
  then
    AVRG_5="HIGH"
  else
    AVRG_5="OK"
  fi
  AVERAGE_15=$(echo "$AVERAGES" | cut -d"," -f3)
  if [[ "$AVERAGE_15" > "$HIGH_AVERAGE"  ]]
  then
    AVRG_15="HIGH"
  else
    AVRG_15="OK"
  fi

  if [[ $plusCPU == "NO" ]]
  then
    if [[ $AVRG_1 == "HIGH" ]] && [[ $AVRG_5 == "HIGH" ]] && [[ $AVRG_15 == "HIGH" ]]
    then
      echo "WARNING: $(date) - Load Averages are too high" | tee -a ${LOG_FILE}
      if [[ $TELEGRAM_ALERTS == "YES" ]]
      then
        bash "${NVOC}/telegram"
      fi
      if [[ $HIGH_LOAD_REBOOT  == "YES" ]]
      then
        echo "WARNING: $(date) - Rebooting system in 5 sec" | tee -a ${LOG_FILE}
        sleep 5
        if [[ SYSRQ_REBOOT == "YES"  ]]
        then
          sudo bash ${NVOC}/sysrq_reboot.sh
        else
          sudo reboot -f
        fi
      fi
    fi
  fi


  sleep 30
done
