#!/bin/bash
export NVOC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${NVOC}/1bash

# Prevent too many reboots
if (( REBOOT_TIMEOUT_IN_MINUTES < 60 ))
then
  REBOOT_TIMEOUT_IN_MINUTES=60
fi

TIMEIN=$REBOOT_TIMEOUT_IN_MINUTES
TIMEOUT=$(($TIMEIN * 60))

sleep 2

echo ""
echo "$(date) - Auto Reboot activated, Rebooting system in $(($TIMEIN / 60 )) Hours"

sleep $TIMEOUT
echo "$(date) - Reboot timer reached, Rebooting system in 10 seconds" | tee -a /home/m1/5_watchdoglog
sleep 10
pkill -ef gnome-terminal
pkill -ef screenrc
pkill -ef 3main
sudo reboot
