#!/bin/bash
# whttomine.com auto switch for nvOC by fullzero , v0019.2 unofficial by papampi
# Feel free to use, change, edit and do what you want with it.

source /home/m1/1bash

# Creating a log file to record coin switch
LOG_FILE="/home/m1/nvoc_logs/8_wtmautoswitchlog"
if [[ -e "$LOG_FILE" ]] ; then
  #Limit the logfile, just keep the last 5K
  echo "$(cat $LOG_FILE | tail -n 5k)" > $LOG_FILE
fi

WTM_HISTORY="/home/m1/WTM_switch_history"
if [[ -e "$WTM_HISTORY" ]] ; then
  #Limit the logfile, just keep the last 100 lines
  echo "$(cat $WTM_HISTORY | tail -n 100)" > $WTM_HISTORY
fi

while true
do

  if [[ $AUTO_START_MINER == "YES" ]]
  then

    python2.7 '/home/m1/WTM_SWITCHER' /home/m1/WTM.json  | tee -a $LOG_FILE
    sleep 5

    CURRENT_COIN=$(head -n 150 /home/m1/1bash | grep COIN= | sed 's/COIN=//' | sed 's/\"//' | sed 's/\"//')
    TOP_COIN=$(cat /home/m1/WTM_top_coin | grep : | sed 's/:[0-9][0-9]//' | sed 's/[0-9]//')
    TIMEIN=$WTM_AUTO_SWITCH_SYNC_INTERVAL
    TIMEOUT=$(($TIMEIN * 60))

    if [[ "$CURRENT_COIN" != "$TOP_COIN" ]]
    then
      sed -i 's/'COIN=\"$CURRENT_COIN\"'/'COIN=\"$TOP_COIN\"/'' /home/m1/1bash
      cat /home/m1/WTM_current_revenue | grep `cat /home/m1/WTM_top_coin | awk -F: '{print $1}'` | awk -F: '{print $2}' >> /home/m1/WTM_24H_REV
      SYNC_COUNT=$((`expr 1440 / $WTM_AUTO_SWITCH_SYNC_INTERVAL`))
      echo "$(tail -$SYNC_COUNT WTM_24H_REV)" > /home/m1/WTM_24H_REV
      sed -i '/^$/d' /home/m1/WTM_24H_REV
      sleep 1

      if  [[ $ALGO_SPECIFIC_OC == "NO" ]]
      then
        echo "Switching Coin with Algo_OC=No, Restarting miner" | tee -a $LOG_FILE
        echo "" | tee -a $LOG_FILE

        while [[ -z  $(ps ax | grep -i screen | grep miner) ]]
        do
          echo "Miner not started yet" | tee -a $LOG_FILE
          echo "" | tee -a $LOG_FILE
          sleep 5
        done

        if [[ -n  $(ps ax | grep -i screen | grep miner) ]]
        then
          echo "Miner is running, lets make the switch" | tee -a $LOG_FILE
          #kill miner
          pkill -e miner
          if [[ $MINER_WATCHDOG == "YES" ]]
          then
            #restart wdog
            pkill -f 5watchdog
            sleep 1
            screen -dmS wdog bash /home/m1/5watchdog
            echo "" | tee -a $LOG_FILE
            echo "wdog restarted in screen wdog; attach with: screen -r wdog" | tee -a $LOG_FILE
            echo "" | tee -a $LOG_FILE
          fi

          #start new miner
          echo "    Commencing Miner Start Command" | tee -a $LOG_FILE
          bash /home/m1/0miner
          echo $( ps ax | grep miner | grep -o 'SCREEN.*' ) | tee -a $LOG_FILE
          echo "process in screen miner; attach with: screen -r miner" | tee -a $LOG_FILE
          echo "" | tee -a $LOG_FILE
        fi

      elif [[ $ALGO_SPECIFIC_OC == "YES"  ]]
      then
        echo "Switching Coin with ALGO_OC=YES, Restart 3main"  | tee -a $LOG_FILE
        pkill -f 5watchdog
        pkill -f 3main
      fi

      echo "$(date) Mining switched from $CURRENT_COIN to $TOP_COIN" | tee -a $LOG_FILE $WTM_HISTORY
      echo "Check again in $TIMEOUT seconds" | tee -a $LOG_FILE
      sleep $TIMEOUT
    else
      echo ""
      echo "$(date) Same Coin on Top, Continue mining $CURRENT_COIN"   | tee -a $LOG_FILE
      echo "Check again in $TIMEOUT seconds" | tee -a $LOG_FILE
      sleep 1
      cat /home/m1/WTM_current_revenue | grep `cat /home/m1/WTM_top_coin | awk -F: '{print $1}'` | awk -F: '{print $2}' >> /home/m1/WTM_24H_REV
      SYNC_COUNT=$((`expr 1440 / $WTM_AUTO_SWITCH_SYNC_INTERVAL`))
      echo "$(tail -$SYNC_COUNT WTM_24H_REV)" > /home/m1/WTM_24H_REV
      sed -i '/^$/d' /home/m1/WTM_24H_REV
      sleep $TIMEOUT
    fi
  else
    echo "Auto start miner set to NO" | tee -a $LOG_FILE
  fi
done
