#!/bin/bash
##########################################################################
#################   nvOC v0019-2.0 - Community Release   #################
##############        by papampi, Stubo and leenoox         ##############
##########   Based on the original nvOC v0019-1.4 by fullzero   ##########
##########################################################################


#                              POOL SWITCH for nvOC v0019-2.1 by papampi                                #
# Changelog:                                                                                            #
# v=0001 : papampi                                                                                      #
#        : Initial Release            
# v=0002 : LukePicci
#          Relocate nvOC to arbitrary install directory

nvOC_Ver="nvOC v0019-2.1 - Community Release"
nvOC_poolswitch_ver="v0019-2.1.0002"
echo "Pool Switch for nvOC $nvOC_poolswitch_ver by papampi"

WDOG_LOG="${NVOC}/5_watchdoglog"
MINER_LOG="${NVOC}/nvoc_logs/screenlog.0"
WTM_LOG="${NVOC}/nvoc_logs/8_wtmautoswitchlog"

source ${NVOC}/1bash
eval 'COIN_POOL=${COIN}_POOL'
eval 'COIN_PORT=${COIN}_PORT'
eval 'COIN_POOL_1=${COIN}_POOL_1'
eval 'COIN_PORT_1=${COIN}_PORT_1'
eval 'COIN_POOL_2=${COIN}_POOL_2'
eval 'COIN_PORT_2=${COIN}_PORT_2'

WTM=0
POOL=1
while !  nc -vzw1 ${!COIN_POOL_1} ${!COIN_PORT_1}
do
  source ${NVOC}/1bash
  POOL=0
  if [[ ${!COIN_POOL} == ${!COIN_POOL_1} ]];  then
    echo "Switching Pool to ${!COIN_POOL_2}:${!COIN_PORT_2}" | tee -a $MINER_LOG $WDOG_LOG
    sed -i 's/'"$COIN_POOL"'=$'"$COIN_POOL_1"'/'"$COIN_POOL"'=$'"$COIN_POOL_2"'/g' ${NVOC}/1bash
    sed -i 's/'"$COIN_PORT"'=$'"$COIN_PORT_1"'/'"$COIN_PORT"'=$'"$COIN_PORT_2"'/g' ${NVOC}/1bash
    echo "Restarting miner and watchdog to complete switching" | tee -a $MINER_LOG $WDOG_LOG
    if [[ $AUTO_SWITCH == WTM_SWITCHING ]]; then
      WTM=1
      echo "Pool Switch is turning off WTM Auto Switch to prevent mixing coin data while ${!COIN_POOL_1} is down" | tee -a $WTM_LOG
      sed -i 's/AUTO_SWITCH="WTM_SWITCHING"/AUTO_SWITCH="NO"/g'  ${NVOC}/1bash
      pkill -f 8wtm_auto_switch
    fi
    pkill -f 5watchdog
    pkill -f 3main
  fi
  echo "Main Pool ${!COIN_POOL_1} not reachable, check again in 5 minutes"
  sleep 300
done


if nc -vzw1 ${!COIN_POOL_1} ${!COIN_PORT_1} && [[ $POOL == 0 ]]; then
  echo "Main Pool ${!COIN_POOL_1}:${!COIN_PORT_1} is reachable now" | tee -a $MINER_LOG $WDOG_LOG
  echo "Switch back to main pool" 
  sed -i 's/'"$COIN_POOL"'=$'"$COIN_POOL_2"'/'"$COIN_POOL"'=$'"$COIN_POOL_1"'/g' ${NVOC}/1bash
  sed -i 's/'"$COIN_PORT"'=$'"$COIN_PORT_2"'/'"$COIN_PORT"'=$'"$COIN_PORT_1"'/g' ${NVOC}/1bash
  if [[ $WTM == 1 ]] ; then
    echo "Pool Switch is turning back on WTM Auto Switch"  | tee -a $WTM_LOG
    sed -i 's/AUTO_SWITCH="NO"/AUTO_SWITCH="WTM_SWITCHING"/g' ${NVOC}/1bash
  fi
  echo "Restarting miner and watchdog to complete switching back to ${!COIN_POOL_1}" | tee -a $MINER_LOG $WDOG_LOG
  pkill -f 5wathcdog
  pkill -f 3main
fi
