#!/bin/bash

DEVICE_IDS=$(nvidia-smi --query-gpu=pci.sub_device_id --format=csv,noheader,nounits)
i=0

for ID in $DEVICE_IDS
do
  VENDOR_ID=${ID:6:5}

  # GPU Query, 3842=EVGA, 1462=MSI, 10DE=Nvidia, 19DA=Zotac, 807D=Asus, 1458=Gigabyte
  case $VENDOR_ID in
    3842) VENDOR_ID="EVGA";;
    1462) VENDOR_ID="MSI";;
    10DE) VENDOR_ID="NVIDIA";;
    19DA) VENDOR_ID="ZOTAC";;
    807D) VENDOR_ID="ASUS";;
    1458) VENDOR_ID="GIGABYTE";;
  esac

  MODEL=$(nvidia-smi -i $i --query-gpu=name --format=csv,noheader,nounits | tail -1)

  echo "$i,$VENDOR_ID,$MODEL"

  i=$(($i + 1))
done