#!/bin/bash
# log rotation by papampi for nvOC by fullzero, v0019-2.0 Community Release

export NVOC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${NVOC}/1bash

nvOC_log_rotate_Dev="0001"
log_rotate_ver="$nvOC_Ver.$nvOC_log_rotate_Dev"

echo "Log Rotate for nvOC $nvOC_Ver"
echo "Version: $log_rotate_ver" 
echo ""
while true
do

  TIMEIN=$LOG_ROTATE_INTERVAL
  TIMEOUT=$(($TIMEIN * 3600))


# Rotating wdog logs
WDOG_LOG_FILE="${NVOC}/5_watchdoglog"
if [ -e "$WDOG_LOG_FILE" ] ; then
  if [ $(wc -c < "$WDOG_LOG_FILE")  -ge 200000 ]; then
    #Limit the logfile, just keep the last 100 lines
    echo "$(tail -100 $WDOG_LOG_FILE)" > $WDOG_LOG_FILE
  fi
fi

# Rotating temp logs
TEMP_LOG_FILE="${NVOC}/6_autotemplog"
if [ -e "$TEMP_LOG_FILE" ] ; then
  if [ $(wc -c < "$TEMP_LOG_FILE") -ge 200000 ]; then
    #Limit the logfile, just keep the last 100 lines
    echo "$(tail -100 $TEMP_LOG_FILE)" > $TEMP_LOG_FILE
  fi
fi
  
  # Rotating watchdog screenlog
  WDOG_SCREEN_LOG_FILE="${NVOC}/nvoc_logs/watchdog-screenlog.0"
  if [ -e "$WDOG_SCREEN_LOG_FILE" ] ; then
    #Limit the logfile, just keep the last 2k
    echo "$(tail -n 2k $WDOG_SCREEN_LOG_FILE)" > $WDOG_SCREEN_LOG_FILE
  fi
  
    # Rotating temp control screenlog
  TEMP_SCREEN_LOG_FILE="${NVOC}/nvoc_logs/tempcontrol-screenlog.0"
  if [ -e "$TEMP_SCREEN_LOG_FILE" ] ; then
    #Limit the logfile, just keep the last 2k
    echo "$(tail -n 2k $TEMP_SCREEN_LOG_FILE)" > $TEMP_SCREEN_LOG_FILE
  fi

  # Rotating screenlog
  MINER_LOG_FILE="${NVOC}/nvoc_logs/screenlog.0"
  if [ -e "$MINER_LOG_FILE" ] ; then
    #Limit the logfile, just keep the last 2k
    echo "$(tail -n 2k $MINER_LOG_FILE)" > $MINER_LOG_FILE
  fi

  # Rotating wtm auto switch logs
  WTM_LOG_FILE="${NVOC}/nvoc_logs/8_wtmautoswitchlog"
  if [ -e "$WTM_LOG_FILE" ] ; then
    #Limit the logfile, just keep the last 2k
    echo "$(tail -n 2k $WTM_LOG_FILE)" > $WTM_LOG_FILE
  fi


  echo "$(date) - Rotate again in $TIMEIN Hours"

  sleep $TIMEOUT
done
