#!/bin/bash
echo " nvOC by fullzero, V0019-2.0 - Community Release"
echo " Backup your old 1bash and any important stuff"
sleep 5

echo "";echo ""

sleep 1;echo "";echo ""
echo "DO NOT OPEN THE TERMINAL OR RESTART THE RIG UNTIL UPDATE IS FINISHED AND EDITED YOUR NEW 1BASH"
echo "";echo ""

echo " Stopping gnome-terminal, miner, wdog, temp, ..."
echo "pkill -f gnome-terminal"
pkill -f gnome-terminal
echo "pkill -f WATCHDOG"
pkill -f WATCHDOG
echo "pkill -f GRAM"
pkill -f GRAM
echo "pkill -f TEMP"
pkill -f TEMP
echo "pkill -f PAPAMPI"
pkill -f PAPAMPI
echo "pkill -e screen"
pkill -e screen

sleep 1;echo "";echo ""

echo "Checking hostname conflict"
if [[ -z $(cat /etc/hosts | grep $(cat /etc/hostname) ) ]]
then
  echo "hostname has conflict, temporarily fixing it"
  echo "sudo hostname m1-desktop"
  sudo hostname m1-desktop
else
  echo "No Problems found"
fi

sleep 1;echo "";echo ""

echo "Fix 19.1-4 fstab problem"

if [[ -z $(cat /etc/fstab | grep "#UUID=55184403759586FB")  ]] && [[ -n $(cat /etc/fstab | grep "UUID=55184403759586FB") ]]
then
  echo "sudo sed -i -e 's/UUID=55184403759586FB/#UUID=55184403759586FB/g' /etc/fstab"
  sudo sed -i -e 's/UUID=55184403759586FB/#UUID=55184403759586FB/g' /etc/fstab
elif [[ -z $(cat /etc/fstab | grep "#/dev/disk/by-id/usb-SanDisk_Cruzer_Blade_4C530001260812105231") ]] && [[ -n $(cat /etc/fstab | grep "/dev/disk/by-id/usb-SanDisk_Cruzer_Blade_4C530001260812105231") ]]
then
  echo "sudo sed -i -e 's\/dev/disk/by-id/usb-SanDisk_Cruzer_Blade_4C530001260812105231\#/dev/disk/by-id/usb-SanDisk_Cruzer_Blade_4C530001260812105231\g' /etc/fstab"
  sudo sed -i -e 's\/dev/disk/by-id/usb-SanDisk_Cruzer_Blade_4C530001260812105231\#/dev/disk/by-id/usb-SanDisk_Cruzer_Blade_4C530001260812105231\g' /etc/fstab
else
  echo "fstab has no problem"
fi


sleep 1;echo "";echo ""

echo "sudo dpkg --configure -a"
sudo dpkg --configure -a
echo "Updating and Upgrading system packages and installing needed packages"
sudo -- sh -c 'apt update; apt upgrade -y; apt autoremove -y; apt autoclean -y; sudo apt install -y moreutils gawk'


sleep 1;echo "";echo ""

if [[ -z  $(cat /etc/screenrc | grep nvoc_log) ]]
then
  echo "Moving miner screenlog.o to tmpf to lower disk read/writes"
  echo "sudo echo logfile  /home/m1/nvoc_logs/screenlog.0 | sudo tee -a  /etc/screenrc"
  sudo echo "logfile  /home/m1/nvoc_logs/screenlog.0" | sudo tee -a  /etc/screenrc
  sleep 1;echo "";echo ""
else
  echo "screen settings for screenlog.0 is ok"
fi

sleep 1;echo "";echo ""

if [[ -z  $(cat /etc/fstab | grep nvoc_log) ]]
then
  echo "making tmpfs nvoc_logs folder for logs"
  sleep 1;echo "";echo ""
  echo "mkdir -p /home/m1/nvoc_logs"
  mkdir -p /home/m1/nvoc_logs
  echo "sudo echo tmpfs /home/m1/nvoc_logs tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=512M 0 0 | sudo tee -a   /etc/fstab"
  sudo echo "tmpfs /home/m1/nvoc_logs tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=512M 0 0" | sudo tee -a   /etc/fstab
  echo "sudo mount -a"
  sudo mount -a
else
  echo "tmpfs nvoc_logs already created"
fi

sleep 1;echo "";echo ""

mkdir -p /home/m1/Downloads/miners
echo "cd /home/m1/Downloads/miners"
cd /home/m1/Downloads/miners

echo "Checking DSTM zm miner 0.5.7"
if [ ! $(cat /home/m1/zec/zm/latest/version | grep 0.5.7) ]
then
  echo "Downloading and making changes for DSTM ZM miner 0.5.7"
  echo "Downloading dstm zm miner 5_7"
  mkdir -p /home/m1/Downloads/miners
  echo "cd /home/m1/Downloads/miners"
  cd /home/m1/Downloads/miners
  if [ -e /home/m1/Downloads/miners/DSTM_0.5.7.tar.gz ]
  then
    echo "Remove Old DSTM"
    rm /home/m1/Downloads/miners/DSTM_0.5.7.tar.gz
  fi
  wget https://www.dropbox.com/s/vpbdwv87j8a7wdl/DSTM_0.5.7.tar.gz
  echo "Extracting the zm miner"
  tar -xvzf DSTM_0.5.7.tar.gz
  rm DSTM_0.5.7.tar.gz
  echo "mkdir -p /home/m1/zec/zm/5_7"
  mkdir -p /home/m1/zec/zm/5_7
  echo "cp -R /home/m1/Downloads/miners/5_7 /home/m1/zec/zm/5_7"
  cp -R /home/m1/Downloads/miners/5_7 /home/m1/zec/zm/
  echo "chmod a+x /home/m1/zec/zm/5_7/zm_miner"
  chmod a+x /home/m1/zec/zm/5_7/zm_miner
  mkdir -p /home/m1/zec/zm/latest
  echo "cp -R /home/m1/zec/zm/5_7/ /home/m1/zec/zm/latest/"
  cp -R /home/m1/zec/zm/5_7/* /home/m1/zec/zm/latest/
  echo "chmod a+x /home/m1/zec/zm/latest/zm_miner"
  chmod a+x /home/m1/zec/zm/latest/zm_miner
else
  echo "DSTM zm miner 0.5.7 already downloaded"
fi

sleep 1;echo "";echo ""

echo "Checking Claymore directory"
if [[ ! -d /home/m1/eth/claymore/ ]]
then
  echo "Moving claymore old miners"
  echo "mkdir -p /home/m1/eth/claymore/"
  mkdir -p /home/m1/eth/claymore/
  echo "mkdir -p /home/m1/eth/claymore/10_2"
  mkdir -p /home/m1/eth/claymore/10_2
  echo "mkdir -p /home/m1/eth/claymore/latest"
  mkdir -p /home/m1/eth/claymore/latest
  echo "cd /home/m1/eth/"
  cd /home/m1/eth/
  echo "cp -r 8_0 9_4 9_5 9_7 9_8 10_0 /home/m1/eth/claymore/"
  cp -r 8_0 9_4 9_5 9_7 9_8 10_0 /home/m1/eth/claymore/
  echo "rm -rf 8_0 9_4 9_5 9_7 9_8 10_0 "
  rm -rf 8_0 9_4 9_5 9_7 9_8 10_0
else
  echo "Claymore directory structre already fixed"
fi

sleep 1;echo "";echo ""

echo "Checking Claymore 10.02"

if [ ! $(cat /home/m1/eth/claymore/latest/version | grep 10.02) ]
then
  echo "Downloading and making changes for Claymore 10_2"
  mkdir -p /home/m1/Downloads/miners
  echo "cd /home/m1/Downloads/miners"
  cd /home/m1/Downloads/miners
  if [ -e /home/m1/Downloads/miners/Claymore-v10.2.tar.gz ]
  then
    echo "Remove Old Claymore"
    rm /home/m1/Downloads/miners/Claymore-v10.2.tar.gz
  fi
  wget https://www.dropbox.com/s/dbwl2bs4olazyh6/Claymore-v10.2.tar.gz
  echo "tar -xvzf Claymore-v10.2.tar.gz"
  tar -xvzf Claymore-v10.2.tar.gz
  rm Claymore-v10.2.tar.gz
  mkdir -p /home/m1/eth/claymore/10_2/
  cp -R /home/m1/Downloads/miners/Claymore-v10.2/* /home/m1/eth/claymore/10_2/
  mkdir -p /home/m1/eth/claymore/latest/
  echo "cp -R /home/m1/eth/claymore/10_2/* /home/m1/eth/claymore/latest/"
  cp -R /home/m1/eth/claymore/10_2/* /home/m1/eth/claymore/latest/
  echo "chmod a+x /home/m1/eth/claymore/*/ethdcrminer64"
  chmod a+x  /home/m1/eth/claymore/latest/ethdcrminer64
else
  echo "Claymore-v10.2 already downloaded"
fi

sleep 1;echo "";echo ""

echo "Checking Tpruvot ccminer-2.2.3"
if [ ! $(cat /home/m1/TPccminer/version | grep 2.2.3) ]
then
  mkdir -p /home/m1/Downloads/miners
  echo "cd /home/m1/Downloads/miners"
  cd /home/m1/Downloads/miners
  echo "Downloading Tpruvot 2.2.3"
  if [ -e /home/m1/Downloads/miners/ccminer-2.2.3-tpruvot.tar.gz ]
  then
    echo "Remove Old Tpruvot ccminer"
    rm /home/m1/Downloads/miners/ccminer-2.2.3-tpruvot.tar.gz
  fi
  echo "wget -c https://www.dropbox.com/s/ys9pgw0cvmfwd0y/ccminer-2.2.3-tpruvot.tar.gz"
  wget -c https://www.dropbox.com/s/ys9pgw0cvmfwd0y/ccminer-2.2.3-tpruvot.tar.gz
  echo "Extracting Tpruvot 2.2.3"
  tar -xvzf ccminer-2.2.3-tpruvot.tar.gz
  rm ccminer-2.2.3-tpruvot.tar.gz
  mkdir -p /home/m1/TPccminer/
  echo "cp -R /home/m1/Downloads/miners/TPccminer/ /home/m1/TPccminer/"
  cp -R /home/m1/Downloads/miners/TPccminer/* /home/m1/TPccminer/
else
  echo "Tpccminer-2.2.3 already downloaded"
fi

sleep 1;echo "";echo ""
echo "Checking KlausT ccminer 8.15"
if [ ! $( cat /home/m1/KTccminer/version | grep 8.15) ]
then
  mkdir -p /home/m1/Downloads/miners
  echo "cd /home/m1/Downloads/miners"
  cd /home/m1/Downloads/miners
  if [ -e /home/m1/Downloads/miners/KTccminer-8.15.tar.gz ]
  then
    echo "Remove Old KTccminer-8.15"
    rm /home/m1/Downloads/miners/KTccminer-8.15.tar.gz
  fi
  echo "Downloading Klaust ccminer"
  echo "wget -c https://www.dropbox.com/s/zqa9mqt5zzx8owr/KTccminer-8.15.tar.gz"
  wget -c https://www.dropbox.com/s/zqa9mqt5zzx8owr/KTccminer-8.15.tar.gz
  echo "Extracting KTccminer-8.15.tar.gz"
  tar -xvzf KTccminer-8.15.tar.gz
  rm KTccminer-8.15.tar.gz
  echo "cp -R /home/m1/Downloads/miners/KTccminer/* /home/m1/KTccminer/"
  mkdir -p /home/m1/KTccminer/
  cp -R /home/m1/Downloads/miners/KTccminer/* /home/m1/KTccminer/
else
  echo "KTccminer-8.15 already downloaded"
fi

sleep 1;echo "";echo ""
echo "Checking vertminer-1.8.3r4"
if [ ! $( cat /home/m1/vertminer/version | grep 1.8.3r4 ) ]
then
  mkdir -p /home/m1/Downloads/miners
  echo "cd /home/m1/Downloads/miners"
  cd /home/m1/Downloads/miners
  if [ -e /home/m1/Downloads/miners/vertminer-1.8.3r4.tar.gz ]
  then
    echo "Remove Old vertminer"
    rm /home/m1/Downloads/miners/vertminer-1.8.3r4.tar.gz
  fi
  echo "Downloading vertminer-1.8.3r4"
  echo "https://www.dropbox.com/s/0mhxbcu0v1c7pfj/vertminer-1.8.3r4.tar.gz"
  wget -c https://www.dropbox.com/s/0mhxbcu0v1c7pfj/vertminer-1.8.3r4.tar.gz
  echo "Extracting vertminer-1.8.3r4.tar.gz"
  tar -xvzf vertminer-1.8.3r4.tar.gz
  rm vertminer-1.8.3r4.tar.gz
  mkdir -p /home/m1/vertminer/
  echo "cp -R /home/m1/Downloads/miners/vertminer/* /home/m1/vertminer/"
  cp -R /home/m1/Downloads/miners/vertminer/* /home/m1/vertminer/
else
  echo "vertminer-1.8.3r4 already downloaded"
fi

sleep 1;echo "";echo ""
echo "Checking nanashi-ccminer-2.2"
if [ ! $(cat /home/m1/NAccminer/version | grep 2.2 ) ]
then
  mkdir -p /home/m1/Downloads/miners
  echo "cd /home/m1/Downloads/miners"
  cd /home/m1/Downloads/miners
  if [ -e /home/m1/Downloads/miners/nanashi-ccminer-2.2.tar.gz ]
  then
    echo "Remove Old nanashi ccminer"
    rm /home/m1/Downloads/miners/nanashi-ccminer-2.2.tar.gz
  fi
  echo "Downloading nanashi ccminer 2.2"
  wget -c https://www.dropbox.com/s/fw4aqkr0ke3hbvt/nanashi-ccminer-2.2.tar.gz
  echo "Extracting nanashi-ccminer-2.2.tar.gz"
  tar -xvzf nanashi-ccminer-2.2.tar.gz
  rm nanashi-ccminer-2.2.tar.gz
  mkdir -p /home/m1/NAccminer/
  echo "cp -R /home/m1/Downloads/miners/nanashi-ccminer/* /home/m1/NAccminer/"
  cp -R /home/m1/Downloads/miners/nanashi-ccminer/* /home/m1/NAccminer/
else
  echo "nanashi-ccminer-2.2 already downloaded"
fi

sleep 1;echo "";echo ""
echo "Checking KXccminer-skunk-2.2"
if [ ! $( cat /home/m1/KXccminer-skunk/version | grep 2.2) ]
then
  mkdir -p /home/m1/Downloads/miners
  echo "cd /home/m1/Downloads/miners"
  cd /home/m1/Downloads/miners
  if [ -e /home/m1/Downloads/miners/KXccminer-skunk-2.2.tar.gz ]
  then
    echo "Remove Old krnlx ccminer"
    rm /home/m1/Downloads/miners/KXccminer-skunk-2.2.tar.gz
  fi
  echo "Downloading krnlx ccminer 2.2"
  wget -c https://www.dropbox.com/s/c3ogj353mmaumua/KXccminer-skunk-2.2.tar.gz
  echo "Extracting KXccminer-skunk-2.2.tar.gz"
  tar -xvzf KXccminer-skunk-2.2.tar.gz
  rm KXccminer-skunk-2.2.tar.gz
  mkdir -p /home/m1/KXccminer-skunk/
  echo "cp -R /home/m1/Downloads/miners/KXccminer-skunk/* /home/m1/KXccminer-skunk/"
  cp -R /home/m1/Downloads/miners/KXccminer-skunk/* /home/m1/KXccminer-skunk/
else
  echo "KXccminer-skunk-2.2 already downloaded"
fi

echo "Downloading new miners finished"

sleep 1;echo "";echo ""

cd /home/m1/Downloads
echo "Downloading V0019-2.0 - Community Release"
if [ -e /home/m1/Downloads/nvOC-19-2.tar.gz ]
then
  rm /home/m1/Downloads/nvOC-19-2.tar.gz
fi
wget https://www.dropbox.com/s/bajt2gaf87kgjrp/nvOC-19-2.tar.gz
echo "Extracting the update files"
tar -xvzf nvOC-19-2.tar.gz
echo "Making sure update files are in correct format"
dos2unix /home/m1/Downloads/nvOC-19-2/*

sleep 1;echo "";echo ""

echo " Checking hostname and permanently fixing it if there is conflict"
if [[ -z $(cat /etc/hosts | grep $(cat /etc/hostname) ) ]]
then
  echo "hostname has conflict, Permanently fixing it"
  echo "sudo cp /home/m1/Downloads/nvOC-19-2/hosts /etc/hosts"
  sudo cp /home/m1/Downloads/nvOC-19-2/hosts /etc/hosts
  echo "sudo cp /home/m1/Downloads/nvOC-19-2/hostname /etc/hostname"
  sudo cp /home/m1/Downloads/nvOC-19-2/hostname /etc/hostname
else
  echo "hostname had no conflicts"
fi

sleep 1;echo "";echo ""

if [ ! -d /home/m1/backups/old_to_19.2 ]
then
  echo "Making a backup of changed files in /home/m1/backups"
  echo "mkdir -p /home/m1/backups"
  mkdir -p /home/m1/backups
  echo "mkdir -p /home/m1/backups/old_to_19.2"
  mkdir -p /home/m1/backups/old_to_19.2
  sleep 1;echo "";echo ""
  echo "cp /home/m1/1bash /home/m1/backups/old_to_19.2/1bash.bak"
  cp /home/m1/1bash /home/m1/backups/old_to_19.2/1bash.bak
  echo "cp /home/m1/3main /home/m1/backups/old_to_19.2/3main.bak"
  cp /home/m1/3main /home/m1/backups/old_to_19.2/3main.bak
  echo "mv /home/m1/Maxximus007_AUTO_TEMPERATURE_CONTROL /home/m1/backups/old_to_19.2/Maxximus007_AUTO_TEMPERATURE_CONTROL.bak"
  mv /home/m1/Maxximus007_AUTO_TEMPERATURE_CONTROL /home/m1/backups/old_to_19.2/Maxximus007_AUTO_TEMPERATURE_CONTROL.bak
  echo "mv /home/m1/IAmNotAJeep_and_Maxximus007_WATCHDOG /home/m1/backups/old_to_19.2/IAmNotAJeep_and_Maxximus007_WATCHDOG.bak"
  mv /home/m1/IAmNotAJeep_and_Maxximus007_WATCHDOG /home/m1/backups/old_to_19.2/IAmNotAJeep_and_Maxximus007_WATCHDOG.bak
  echo "mv /home/m1/PAPAMPI_WTM /home/m1/backups/old_to_19.2/PAPAMPI_WTM.bak"
  mv /home/m1/PAPAMPI_WTM /home/m1/backups/old_to_19.2/PAPAMPI_WTM.bak
  echo "mv /home/m1/PAPAMPI_PROFIT_CHECK /home/m1/backups/old_to_19.2/PAPAMPI_PROFIT_CHECK.bak"
  mv /home/m1/PAPAMPI_PROFIT_CHECK /home/m1/backups/old_to_19.2/PAPAMPI_PROFIT_CHECK.bak
  echo "mv /home/m1/WTM_AUTO_SWITCH /home/m1/backups/old_to_19.2/WTM_AUTO_SWITCH.bak"
  mv /home/m1/WTM_AUTO_SWITCH /home/m1/backups/old_to_19.2/WTM_AUTO_SWITCH.bak
  echo "cp /home/m1/2unix /home/m1/backups/old_to_19.2/2unix.bak"
  cp /home/m1/2unix /home/m1/backups/old_to_19.2/2unix.bak
else
  echo "No new backups, already have backups in /home/m1/backups/old_to_19.2"
fi
if [ -e /home/m1/BaliMiner_TELEGRAM_ALERTS ];then
  echo "mv /home/m1/BaliMiner_TELEGRAM_ALERTS /home/m1/backups/old_to_19.2/BaliMiner_TELEGRAM_ALERTS.bak"
  mv /home/m1/BaliMiner_TELEGRAM_ALERTS /home/m1/backups/old_to_19.2/BaliMiner_TELEGRAM_ALERTS.bak
fi

sleep 1;echo "";echo ""

echo "Copying updates"

sleep 1;echo "";echo ""

echo "cp /home/m1/Downloads/nvOC-19-2/2unix /home/m1/2unix"
cp /home/m1/Downloads/nvOC-19-2/2unix /home/m1/2unix
echo "cp /home/m1/Downloads/nvOC-19-2/0miner /home/m1/0miner"
cp /home/m1/Downloads/nvOC-19-2/0miner /home/m1/0miner
echo "cp /home/m1/Downloads/nvOC-19-2/3main /home/m1/3main"
cp /home/m1/Downloads/nvOC-19-2/3main /home/m1/3main
echo "cp /home/m1/Downloads/nvOC-19-2/log_rotate /home/m1/log_rotate"
cp /home/m1/Downloads/nvOC-19-2/log_rotate /home/m1/log_rotate
echo "cp /home/m1/Downloads/nvOC-19-2/ext/minerinfo /home/m1/www/cgi-bin/minerinfo"
cp /home/m1/Downloads/nvOC-19-2/ext/minerinfo /home/m1/www/cgi-bin/minerinfo
echo "cp /home/m1/Downloads/nvOC-19-2/ext/clearalerts /home/m1/www/cgi-bin/clearalerts"
cp /home/m1/Downloads/nvOC-19-2/ext/clearalerts /home/m1/www/cgi-bin/clearalerts

echo "cp /home/m1/Downloads/nvOC-19-2/telegram /home/m1/telegram"
cp /home/m1/Downloads/nvOC-19-2/telegram /home/m1/telegram
echo "cp /home/m1/Downloads/nvOC-19-2/6tempcontrol /home/m1/6tempcontrol"
cp /home/m1/Downloads/nvOC-19-2/6tempcontrol /home/m1/6tempcontrol
echo "cp /home/m1/Downloads/nvOC-19-2/5watchdog /home/m1/5watchdog"
cp /home/m1/Downloads/nvOC-19-2/5watchdog /home/m1/5watchdog
echo "cp /home/m1/Downloads/nvOC-19-2/8wtm_auto_switch /home/m1/8wtm_auto_switch"
cp /home/m1/Downloads/nvOC-19-2/8wtm_auto_switch /home/m1/8wtm_auto_switch
echo "cp /home/m1/Downloads/nvOC-19-2/8wtm_profit_check /home/m1/8wtm_profit_check"
cp /home/m1/Downloads/nvOC-19-2/8wtm_profit_check /home/m1/8wtm_profit_check
echo "cp /home/m1/Downloads/nvOC-19-2/ext/WTM_SWITCHER /home/m1/WTM_SWITCHER"
cp /home/m1/Downloads/nvOC-19-2/ext/WTM_SWITCHER /home/m1/WTM_SWITCHER
echo "cp /home/m1/Downloads/nvOC-19-2/screenrc-tempcontrol /home/m1/screenrc-tempcontrol"
cp /home/m1/Downloads/nvOC-19-2/screenrc-tempcontrol /home/m1/screenrc-tempcontrol
echo "cp /home/m1/Downloads/nvOC-19-2/screenrc-watchdog /home/m1/screenrc-watchdog"
cp /home/m1/Downloads/nvOC-19-2/screenrc-watchdog /home/m1/screenrc-watchdog
echo "cp /home/m1/Downloads/nvOC-19-2/nvOC /home/m1/nvOC"
cp /home/m1/Downloads/nvOC-19-2/nvOC /home/m1/nvOC
echo "cp /home/m1/Downloads/nvOC-19-2/7telegram /home/m1/7telegram"
cp /home/m1/Downloads/nvOC-19-2/7telegram /home/m1/7telegram

sleep 1;echo "";echo ""

echo "chmod a+x /home/m1/www/cgi-bin/minerinfo"
chmod a+x /home/m1/www/cgi-bin/minerinfo
echo "chmod a+x /home/m1/www/cgi-bin/clearalerts"
chmod a+x /home/m1/www/cgi-bin/clearalerts
echo "touch /home/m1/5_watchdoglog"
touch /home/m1/5_watchdoglog
echo "touch /home/m1/6_autotemplog"
touch /home/m1/6_autotemplog
echo "touch /home/m1/WTM_switch_history"
touch /home/m1/WTM_switch_history
echo "touch /home/m1/nvoc_logs/screenlog.0"
touch /home/m1/nvoc_logs/screenlog.0
echo "chmod 666 /home/m1/nvoc_logs/*"
chmod 666 /home/m1/nvoc_logs/*
echo "chmod 666 /home/m1/6_autotemplog"
chmod 666 /home/m1/6_autotemplog
echo "chmod 666 /home/m1/5_watchdoglog"
chmod 666 /home/m1/5_watchdoglog
echo "chmod a+x /home/m1/nvOC"
chmod a+x /home/m1/nvOC
sleep 1;echo "";echo ""
echo "cleaning old temp and watchdog logs"
echo " " > /home/m1/5_watchdoglog
echo " " > /home/m1/6_autotemplog

touch /home/m1/.bash_aliases
if [[ -z  $(cat /home/m1/.bash_aliases | grep master-log | grep tempcontrol) ]]
then
  echo "Adding master-log alias"
  sed -i '/^alias master-log/d' /home/m1/.bash_aliases
  echo "alias master-log='tail -f /home/m1/nvoc_logs/screenlog.0 /home/m1/nvoc_logs/tempcontrol-screenlog.0 /home/m1/nvoc_logs/watchdog-screenlog.0 /home/m1/nvoc_logs/8_wtmautoswitchlog'" | tee -a /home/m1/.bash_aliases
  echo "If local_or_remote=remote, run master-log in guake or ssh sessions, to watch all your logs live"
  echo " "
  sleep 5
fi

if [[ -z  $(cat /home/m1/.bash_aliases | grep miner-restart) ]]
then
  echo "Adding miner-restart alias"
  echo "alias miner-restart='pkill -f 5watchdog && pkill -f 3main'" | tee -a /home/m1/.bash_aliases
  echo "run miner-restart in guake or ssh sessions, to restart 3main"
  echo " "
  sleep 5
fi

if [[ -z $(head -n 50 /home/m1/1bash | grep 'v0019-2.0.00' ) ]]; then
  echo "**************************************************************************************************************************"
  echo "**************************************************************************************************************************"
  echo "**************************************************************************************************************************"
  echo "**************************************************************************************************************************"
  echo "                                             1bash was not v0019-2.0.00*"
  echo "                                     Old 1bash copied to /home/m1/backups/1bash.old"
  echo "                               New 1bash v0019-2.0.002 replaced and added to /home/m1/1bash"
  echo "                                       Dont forget to edit the new 1bash before reboot"
  echo "**************************************************************************************************************************"
  echo "**************************************************************************************************************************"
  echo "**************************************************************************************************************************"
  echo "**************************************************************************************************************************"
  cp /home/m1/1bash /home/m1/backups/1bash.old
  cp /home/m1/Downloads/nvOC-19-2/1bash /home/m1/1bash
fi
if [[ -n $(head -n 50 /home/m1/1bash | grep 'v0019-2.0.001' ) ]]; then
  echo "**************************************************************************************************************************"
  echo "**************************************************************************************************************************"
  echo "**************************************************************************************************************************"
  echo "**************************************************************************************************************************"
  echo "                            Your 1bash is v0019-2.0-001, latest version is v0019-2.0-002"
  echo "                                      Changes will be applied to your 1bash"
  echo "                              Telegram section changed in 1bash, review and edit it"
  echo "**************************************************************************************************************************"
  echo "**************************************************************************************************************************"
  echo "**************************************************************************************************************************"
  sed -i 's/v0019-2.0.001/v0019-2.0.002/g' /home/m1/1bash
  sed -i 's/BaliMiner_TELEGRAM_ALERTS/TELEGRAM_MESSAGES/g' /home/m1/1bash
  sed -i '/TELEGRAM_MESSAGES/a TELEGRAM_ALERTS="YES" # YES or NO # Set to No if you Dont want to get Telegram Alerts'  /home/m1/1bash
  sleep 5
fi

sleep 1;echo "";echo ""

echo "**************************************************************************************************************************"
echo "**************************************************************************************************************************"
echo "                                                             All Done"
echo "                    Old 1bash, 3main, wdog and temp are copied to /home/m1/backups/old_to_19.2/*.bak"
echo "                                Edit your 1bash, Set auto start miner then reboot your rig"
echo "                                                  Keep Calm and Carry on Mining"
echo "**************************************************************************************************************************"
echo "**************************************************************************************************************************"
