#!/bin/bash
echo " nvOC by fullzero, unofficial 19.2 by papampi"
echo " Edits by papampi : Making tmpfs partition for log files to reduce SSD/USB/HDD read /writes, added option to auto start miner or not in 1bash, new 1bash for unified and separated pool and ports for wdog checking if pool is online, new separated 0miner to make 3main lighter and easier start miner, fix hostname conflict, add Warning to wdog and temp logs to ,  and many more edits and bug fixes"
echo " Edits by Stubo: simplified 3main, some wdog fixes, add dstm zm 5_5 version, and many more edits and bug fixes."
echo " Backup your old 1bash and any important stuff"
echo " wait 30 seconds, if you have not backed up hit ctrl+c now"
sleep 1;echo "";echo ""
echo " DO NOT OPEN THE TERMINAL OR RESTART THE RIG UNTIL UPDATE IS FININSHD AND EDITED YOUR NEW 1BASH"
echo "";echo ""
sleep 30;echo "";echo ""

echo " Stopping gnome-terminal, miner, wdog, temp, ..."
echo "pkill -f gnome-terminal"
pkill -f gnome-terminal
echo "pkill -f WATCHDOG"
pkill -f WATCHDOG
echo "pkill -f GRAM"
pkill -f GRAM
echo "pkill -f TEMP"
pkill -f TEMP
echo "pkill -f PAPAMPI"
pkill -f PAPAMPI
echo "pkill -e screen"
pkill -e screen

sleep 1;echo "";echo ""
echo "Checking hostname conflict"
if [[ -z $(cat /etc/hosts | grep $(cat /etc/hostname) ) ]]
then
  echo "hostname has conflict, temporarily fixing it"
  echo "sudo hostname m1-desktop"
  sudo hostname m1-desktop
else
  echo "No Problems found"
fi

sleep 1;echo "";echo ""

echo "Updating and Upgrading system packages and installing needed packages"
sudo apt update && sudo apt upgrade -y
sudo apt install -y moreutils gawk
sudo apt autoclean -y
sudo apt autoremove -y

sleep 1;echo "";echo ""

if [[ -z  $(cat /etc/screenrc | grep nvoc_log) ]]
then
  echo "Moving miner screenlog.o to tmpf to lower disk read/writes"
  echo "sudo echo "logfile  /home/m1/nvoc_logs/screenlog.0" | sudo tee -a  /etc/screenrc"
  sudo echo "logfile  /home/m1/nvoc_logs/screenlog.0" | sudo tee -a  /etc/screenrc
  sleep 1;echo "";echo ""
else
  echo "screen settings for screenlog.0 is ok"
fi

if [[ -z  $(cat /etc/fstab | grep nvoc_log) ]]
then
  echo "making tmpfs nvoc_logs folder for logs"
  sleep 1;echo "";echo ""
  echo "mkdir -p /home/m1/nvoc_logs"
  mkdir -p /home/m1/nvoc_logs
  echo "sudo echo "tmpfs /home/m1/nvoc_logs tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=512M 0 0" | sudo tee -a   /etc/fstab"
  sudo echo "tmpfs /home/m1/nvoc_logs tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=512M 0 0" | sudo tee -a   /etc/fstab
  echo "sudo mount -a"
  sudo mount -a
else
  echo "tmpfs nvoc_logs already created"
fi

if [ ! -d /home/m1/zec/zm/5_6/ ]; then
sleep 1;echo "";echo ""
echo "Downloading dstm zm miner 5_6"
echo "cd /home/m1/Downloads"
cd /home/m1/Downloads
wget https://www.dropbox.com/s/mfk12y75n45q7ff/DSTM_0.5.6.tar.gz
echo "Extracting the zm miner"
tar -xvzf DSTM_0.5.6.tar.gz
echo "mkdir -p /home/m1/zec/zm/5_6"
mkdir -p /home/m1/zec/zm/5_6
echo "mv /home/m1/Downloads/5_6 /home/m1/zec/zm"
mv /home/m1/Downloads/5_6 /home/m1/zec/zm/
echo "chmod a+x /home/m1/zec/zm/5_6/zm"
chmod a+x /home/m1/zec/zm/5_6/zm_miner
echo "mkdir -p /home/m1/zec/zm/latest"
mkdir -p /home/m1/zec/zm/latest
echo "cp /home/m1/zec/zm/5_6/zm_miner /home/m1/zec/zm/latest/zm_miner"
cp /home/m1/zec/zm/5_6/zm_miner /home/m1/zec/zm/latest/zm_miner
echo "chmod a+x /home/m1/zec/zm/latest/zm_miner"
chmod a+x /home/m1/zec/zm/latest/zm_miner
fi

sleep 1;echo "";echo ""

echo "Downloading V19.2 unofficial updates"
wget https://www.dropbox.com/s/bajt2gaf87kgjrp/nvOC-19-2.tar.gz
echo "Extracting the update files"
tar -xvzf nvOC-19-2.tar.gz
echo "Making sure update files are in correct format"
dos2unix /home/m1/Downloads/nvOC-19-2/*

echo " Checking hostname and permanently fixing it if there is conflict"
if [[ -z $(cat /etc/hosts | grep $(cat /etc/hostname) ) ]]
then
  echo "hostanema has conflict, Permanently fixing it"
  echo "sudo cp /home/m1/Downloads/nvOC-19-2/hosts /etc/hosts"
  sudo cp /home/m1/Downloads/nvOC-19-2/hosts /etc/hosts
  echo "sudo cp /home/m1/Downloads/nvOC-19-2/hostname /etc/hostname"
  sudo cp /home/m1/Downloads/nvOC-19-2/hostname /etc/hostname
else
  echo "hostname had no conflicts"
fi

echo "Making a backup of 1bash, 3main, wdog and temp in /home/m1/backups"
echo "mkdir -p /home/m1/backups"
mkdir -p /home/m1/backups
sleep 1;echo "";echo ""

echo "cp /home/m1/1bash /home/m1/backups/1bash.bak"
cp /home/m1/1bash /home/m1/backups/1bash.bak
echo "cp /home/m1/3main /home/m1/backups/3main.bak"
cp /home/m1/3main /home/m1/backups/3main.bak
echo "mv /home/m1/Maxximus007_AUTO_TEMPERATURE_CONTROL /home/m1/backups/Maxximus007_AUTO_TEMPERATURE_CONTROL.bak"
mv /home/m1/Maxximus007_AUTO_TEMPERATURE_CONTROL /home/m1/backups/Maxximus007_AUTO_TEMPERATURE_CONTROL.bak
echo "mv /home/m1/IAmNotAJeep_and_Maxximus007_WATCHDOG /home/m1/backups/IAmNotAJeep_and_Maxximus007_WATCHDOG.bak"
mv /home/m1/IAmNotAJeep_and_Maxximus007_WATCHDOG /home/m1/backups/IAmNotAJeep_and_Maxximus007_WATCHDOG.bak

echo "mv /home/m1/PAPAMPI_WTM /home/m1/backups/PAPAMPI_WTM.bak"
mv /home/m1/PAPAMPI_WTM /home/m1/backups/PAPAMPI_WTM.bak
echo "mv /home/m1/PAPAMPI_PROFIT_CHECK /home/m1/backups/PAPAMPI_PROFIT_CHECK.bak"
mv /home/m1/PAPAMPI_PROFIT_CHECK /home/m1/backups/PAPAMPI_PROFIT_CHECK.bak


echo "Copying updates"
sleep 1
echo " "
echo " "

if [[ -z $(head /home/m1/1bash | grep v0019.2) ]]; then 
  echo "cp /home/m1/Downloads/nvOC-19-2/1bash /home/m1/1bash"
  cp /home/m1/Downloads/nvOC-19-2/1bash /home/m1/1bash
fi

echo "cp /home/m1/Downloads/nvOC-19-2/0miner /home/m1/0miner"
cp /home/m1/Downloads/nvOC-19-2/0miner /home/m1/0miner
echo "cp /home/m1/Downloads/nvOC-19-2/3main /home/m1/3main"
cp /home/m1/Downloads/nvOC-19-2/3main /home/m1/3main
echo "cp /home/m1/Downloads/nvOC-19-2/log_rotate /home/m1/log_rotate"
cp /home/m1/Downloads/nvOC-19-2/log_rotate /home/m1/log_rotate
echo "cp /home/m1/Downloads/nvOC-19-2/www/minerinfo /home/m1/www/cgi-bin/minerinfo"
cp /home/m1/Downloads/nvOC-19-2/www/minerinfo /home/m1/www/cgi-bin/minerinfo
echo "cp /home/m1/Downloads/nvOC-19-2/telegram /home/m1/telegram"
cp /home/m1/Downloads/nvOC-19-2/telegram /home/m1/telegram
echo "cp /home/m1/Downloads/nvOC-19-2/MINER_TEMP_CONTROL /home/m1/MINER_TEMP_CONTROL"
cp /home/m1/Downloads/nvOC-19-2/MINER_TEMP_CONTROL /home/m1/MINER_TEMP_CONTROL
echo "cp /home/m1/Downloads/nvOC-19-2/MINER_WATCHDOG /home/m1/MINER_WATCHDOG"
cp /home/m1/Downloads/nvOC-19-2/MINER_WATCHDOG /home/m1/MINER_WATCHDOG
echo "cp /home/m1/Downloads/nvOC-19-2/8_WTM_AUTO_SWITCH /home/m1/8_WTM_AUTO_SWITCH"
cp /home/m1/Downloads/nvOC-19-2/8_WTM_AUTO_SWITCH /home/m1/8_WTM_AUTO_SWITCH
echo "cp /home/m1/Downloads/nvOC-19-2/WTM_PROFIT_CHECK /home/m1/WTM_PROFIT_CHECK"
cp /home/m1/Downloads/nvOC-19-2/WTM_PROFIT_CHECK /home/m1/WTM_PROFIT_CHECK
echo "cat /home/m1/8_wtmautoswitchlog | grep switch > /home/m1//WTM_switch_history"
cat /home/m1/8_wtmautoswitchlog | grep switch > /home/m1//WTM_switch_history


sleep 1;echo "";echo ""
echo "mv /home/m1/5_restartlog /home/m1/nvoc_logs/5_restartlog"
mv /home/m1/5_restartlog /home/m1/nvoc_logs/5_restartlog
echo "mv /home/m1/screenlog.0 /home/m1/nvoc_logs/screenlog.0"
mv /home/m1/screenlog.0 /home/m1/nvoc_logs/screenlog.0
echo "/home/m1/6_autotemplog /home/m1/nvoc_logs/6_autotemplog"
mv /home/m1/6_autotemplog /home/m1/nvoc_logs/6_autotemplog
echo "chmod a+x /home/m1/www/cgi-bin/minerinfo"
chmod a+x /home/m1/www/cgi-bin/minerinfo
echo "chmod a+x /home/m1/www/cgi-bin/clearalerts"
chmod a+x /home/m1/www/cgi-bin/clearalerts
echo "touch /home/m1/WTM_switch_histrory"
touch /home/m1/WTM_switch_histrory
echo "touch /home/m1/7_wdog_alertlog"
touch /home/m1/7_wdog_alertlog
echo "touch /home/m1/7_temp_alertlog"
touch /home/m1/7_temp_alertlog
echo "chmod 666 /home/m1/nvoc_logs/*"
chmod 666 /home/m1/nvoc_logs/*
echo "chmod 666 /home/m1/7_*"
chmod 666 /home/m1/7_*

echo "chmod 666  /home/m1/nvoc_logs/5_restartlog"
chmod 666  /home/m1/nvoc_logs/5_restartlog
echo "chmod 666 /home/m1/nvoc_logs/screenlog.0"
chmod 666  /home/m1/nvoc_logs/screenlog.0
echo "chmod 666 /home/m1/nvoc_logs/6_autotemplog"
chmod 666 /home/m1/nvoc_logs/6_autotemplog


sleep 1;echo "";echo ""
touch /home/m1/.bash_aliases
if [[ -z  $(cat /home/m1/.bash_aliases | grep master-log) ]]
then
  echo " Adding master-log alias"
  echo "alias master-log='tail -f /home/m1/nvoc_logs/screenlog.0 /home/m1/nvoc_logs/5_restartlog /home/m1/nvoc_logs/6_autotemplog /home/m1/nvoc_logs/8_wtmautoswitchlog' " | tee -a /home/m1/.bash_aliases
  echo "type master-log in guake or ssh sessions, to watch all your logs live"
  echo " "
fi

if [[ -z  $(cat /home/m1/.bash_aliases | grep miner-restart) ]]
then
  echo "Adding miner-restart alias"
  echo "alias miner-restart='pkill -f WATCHDOG & pkill -f 3main'" | tee -a /home/m1/.bash_aliases
  echo "type miner-restart in guake or ssh sessions, to restart 3main"
  echo " "
fi

sleep 1;echo "";echo ""

echo "All Done"
echo "Old 1bash, 3main, wdog and temp are copied to /home/m1/backups/*.bak"
echo "Edit your 1bash then reboot your rig"
echo "Keep Calm and Carry on Mining"
