#!/bin/bash
echo "Roll back from unofficial 19.2 to old one"

sleep 30

echo "cp /home/m1/backups/old_to_19.2/1bash.bak /home/m1/1bash"
cp /home/m1/backups/old_to_19.2/1bash.bak /home/m1/1bash
echo "cp /home/m1/backups/old_to_19.2/3main.bak /home/m1/3main"
cp /home/m1/backups/old_to_19.2/3main.bak /home/m1/3main
echo "mv /home/m1/backups/old_to_19.2/Maxximus007_AUTO_TEMPERATURE_CONTROL.bak /home/m1/Maxximus007_AUTO_TEMPERATURE_CONTROL "
mv /home/m1/backups/old_to_19.2/Maxximus007_AUTO_TEMPERATURE_CONTROL.bak /home/m1/Maxximus007_AUTO_TEMPERATURE_CONTROL
echo "mv /home/m1/backups/old_to_19.2/IAmNotAJeep_and_Maxximus007_WATCHDOG.bak /home/m1/IAmNotAJeep_and_Maxximus007_WATCHDOG"
mv  /home/m1/backups/old_to_19.2/IAmNotAJeep_and_Maxximus007_WATCHDOG.bak /home/m1/IAmNotAJeep_and_Maxximus007_WATCHDOG
echo "mv /home/m1/backups/old_to_19.2/PAPAMPI_WTM.bak /home/m1/PAPAMPI_WTM"
mv /home/m1/backups/old_to_19.2/PAPAMPI_WTM.bak /home/m1/PAPAMPI_WTM
echo "mv /home/m1/backups/old_to_19.2/PAPAMPI_PROFIT_CHECK.bak /home/m1/PAPAMPI_PROFIT_CHECK"
mv /home/m1/backups/old_to_19.2/PAPAMPI_PROFIT_CHECK.bak /home/m1/PAPAMPI_PROFIT_CHECK
echo "mv /home/m1/backups/old_to_19.2/WTM_AUTO_SWITCH.bak /home/m1/WTM_AUTO_SWITCH"
mv /home/m1/backups/old_to_19.2/WTM_AUTO_SWITCH.bak /home/m1/WTM_AUTO_SWITCH
echo "/home/m1/backups/old_to_19.2/2unix.bak cp /home/m1/2unix"
cp /home/m1/backups/old_to_19.2/2unix.bak cp /home/m1/2unix


