#!/bin/bash

export NVOC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${NVOC}/1bash
TIMEOUT=$(($upPASTE_TIMEOUT_IN_MINUTES * 60))
echo ""
echo "checks for a 1bash update every $TIMEOUT seconds"
echo ""

BITCOIN="theGROUND"

while [ $BITCOIN == "theGROUND" ]
do

cd /tmp
wget $pasteBASH       # Assumes the file we are getting is called 1bash
cp '/tmp/1bash' "${NVOC}/temp1bash"
rm '/tmp/1bash'

change="NO"

old=$(md5sum "${NVOC}/1bash" | sed 's/[^0-9]*//g')
echo $old
echo ""
sleep 2
new=$(md5sum "${NVOC}/temp1bash" | sed 's/[^0-9]*//g')
echo $new
echo ""

if [ $old != $new ]
then
  change="YES"
  cp "${NVOC}/temp1bash" "${NVOC}/1bash"
  echo ""
  echo "1bash updated from paste: $pasteBASH"
  echo ""
  sleep 2
  bash ${NVOC}/nvOC restart
fi

if [ $change == "NO" ]
then
echo "no changes"
echo ""
fi
sleep $TIMEOUT
done
fi
