#!/bin/bash
# whttomine.com auto switch for nvOC by fullzero , v0019.2 unofficial by papampi

#Feel free to use, change, edit and do what you want with it.

source /home/m1/1bash

# Creating a log file to record coin switch
LOG_FILE="/home/m1/nvoc_logs/8_wtmautoswitchlog"
if [[ -e "$LOG_FILE" ]] ; then
  #Limit the logfile, just keep the last 5K
  echo "$(cat $LOG_FILE | grep switched | tail -n 5k)" > $LOG_FILE
fi

WTM_HISTORY="/home/m1//WTM_switch_history"
if [[ -e "$WTM_HISTORY" ]] ; then
  #Limit the logfile, just keep the last 2K
  echo "$(cat $WTM_HISTORY | grep switched | tail -n 2k)" > $WTM_HISTORY
fi

while true
do

  if [[ $AUTO_START_MINER == "YES" ]]
  then

    python2.7 '/home/m1/WTM_AUTO_SWITCH' /home/m1/WTM.json  | tee -a $LOG_FILE
    sleep 5

    CURRENT_COIN=$(head -n 150 /home/m1/1bash | grep COIN= | sed 's/COIN=//' | sed 's/\"//' | sed 's/\"//')
    TOP_COIN=$(cat /home/m1/WTM_top_coin | grep : | sed 's/:[0-9][0-9]//' | sed 's/[0-9]//')
    #TOP_COIN=$(cat /home/m1/top_coin)
    TIMEIN=$WTM_AUTO_SWITCH_SYNC_INTERVAL
    TIMEOUT=$(($TIMEIN * 60))

    if [[ "$CURRENT_COIN" != "$TOP_COIN" ]]
    then
      sed -i 's/'COIN=\"$CURRENT_COIN\"'/'COIN=\"$TOP_COIN\"/'' /home/m1/1bash
      cat /home/m1/WTM_current_revenue | grep `cat /home/m1/WTM_top_coin | awk -F: '{print $1}'` | awk -F: '{print $2}' >> /home/m1/WTM_24H_REV
      SYNC_COUNT=$((`expr 1440 / $WTM_AUTO_SWITCH_SYNC_INTERVAL`))
      echo "$(tail -$SYNC_COUNT WTM_24H_REV)" > /home/m1/WTM_24H_REV
      sed -i '/^$/d' /home/m1/WTM_24H_REV
      sleep 1

      if  [[ $damNmad_ALGO_SPECIFIC_OC == "NO" ]]
      then
        echo "'damNmad_ALGO_SPECIFIC_OC=NO', only restarting miner" | tee -a $LOG_FILE
        echo "" | tee -a $LOG_FILE


        while [[ -z  $(ps ax | grep -i screen | grep miner) ]]
        do
          echo "miner not started yet" | tee -a $LOG_FILE $ALERT_LOG_FILE
          echo "" | tee -a $LOG_FILE
          sleep 5
        done

        if [[ -n  $(ps ax | grep -i screen | grep miner) ]]
        then
          echo "miner is running, lets make the switch" | tee -a $LOG_FILE
          #kill miner
          pkill -e miner
          if [ $IAmNotAJeep_and_Maxximus007_WATCHDOG == "YES" ]
          then
            #restart wdog
            pkill -f IAmNotAJeep_and_Maxximus007_WATCHDOG
            sleep 1
            screen -dmS wdog bash /home/m1/IAmNotAJeep_and_Maxximus007_WATCHDOG
            echo "" | tee -a $LOG_FILE
            echo "wdog restarted in screen wdog; attach with: screen -r wdog" | tee -a $LOG_FILE
            echo "" | tee -a $LOG_FILE
          fi

          #start new miner
          echo "    Commencing Miner Start Command" | tee -a $LOG_FILE
          bash /home/m1/0miner
          echo $( ps ax | grep miner | grep -o 'SCREEN.*' ) | tee -a $LOG_FILE
          echo "process in screen miner; attach with: screen -r miner" | tee -a $LOG_FILE
          echo "" | tee -a $LOG_FILE
          echo "$(date) Mining switched from $CURRENT_COIN to $TOP_COIN" | tee -a $LOG_FILE $WTM_HISTORY
          echo "Check again in $TIMEOUT seconds" | tee -a $LOG_FILE
        fi

      elif  [[ $damNmad_ALGO_SPECIFIC_OC == "YES" ]]
      then
        echo "'damNmad_ALGO_SPECIFIC_OC=YES', restarting 3main for OC settings to take effect"  | tee -a $LOG_FILE
        echo "If you dont like too many guake tabs, in 1bash set LOCALorREMOTE=REMOTE "
        pkill -f 3main
      fi
      sleep $TIMEOUT

    else
      echo ""
      echo "$(date) Same Coin on Top, Continue mining $CURRENT_COIN"  # | tee -a $LOG_FILE
      echo "Check again in $TIMEOUT seconds" #| tee -a $LOG_FILE
      sleep 1
      cat /home/m1/WTM_current_revenue | grep `cat /home/m1/WTM_top_coin | awk -F: '{print $1}'` | awk -F: '{print $2}' >> /home/m1/WTM_24H_REV
      SYNC_COUNT=$((`expr 1440 / $WTM_AUTO_SWITCH_SYNC_INTERVAL`))
      echo "$(tail -$SYNC_COUNT WTM_24H_REV)" > /home/m1/WTM_24H_REV
      sed -i '/^$/d' /home/m1/WTM_24H_REV
      sleep $TIMEOUT
    fi

  else
    echo "Auto start miner set to NO"
  fi

done
